// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2016.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc253.Code2016.Robot;

/**
 *
 */
public class Snippet extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Snippet() {
    	

		requires(Robot.ballPickUp);
	
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	setTimeout(1.7);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.ballPickUp.PickUp();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.ballPickUp.FullStop();

    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.ballPickUp.FullStop();
    	end();
    }
}
