// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.Code2016.subsystems;

import org.usfirst.frc253.Code2016.RobotMap;
import org.usfirst.frc253.Code2016.commands.*;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.*;




/**
 *
 */
public class LiftSystem extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SpeedController motor1 = RobotMap.liftSystemTalonLift1WindowMotor;
    private SpeedController motor2 = RobotMap.liftSystemTalonLift2WindowMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {}
        public LiftSystem() {
        	super();
//        	 motor1 = new Talon (5);
//        	 motor2 = new Talon (4);
        	 leftStop();
        	 rightStop();
        	 
        }

    public void leftDown() {
    	motor1.set(-0.4);	
    }
    public void leftStop() {
    	motor1.set(0);
    }

public void rightUp() {
	motor2.set(-0.46);
	
}

public void rightDown() {
	motor2.set(0.40);	
}
public void rightStop() {
	motor2.set(0);
}
public void leftUp() {
	motor1.set(0.49);
	
}
}
    
  
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
   

